#!/usr/bin/env python3
"""Fill empty translations in all .po files from dictionaries."""
import re, sys, os

TRANSLATIONS = {
"uk": {
    "Embedded SSH terminals": "Вбудовані SSH-термінали",
    "Secure credential storage": "Безпечне зберігання облікових даних",
    "Expect automation": "Автоматизація Expect",
    "Groups and tags": "Групи та теги",
    "Zero Trust tunnels": "Тунелі Zero Trust",
    "Customizable settings": "Налаштовувані параметри",
    "Embedded & external clients": "Вбудовані та зовнішні клієнти",
    "New connection": "Нове з'єднання",
    "New group": "Нова група",
    "Local shell": "Локальна оболонка",
    "Quick connect": "Швидке з'єднання",
    "Search": "Пошук",
    "Split vertical": "Розділити вертикально",
    "Split horizontal": "Розділити горизонтально",
    "Next tab": "Наступна вкладка",
    "Smart search caching": "Розумне кешування пошуку",
    "Lazy loading for trees": "Ліниве завантаження дерев",
    "Virtual scrolling": "Віртуальна прокрутка",
    "Embedded VNC/RDP/SPICE": "Вбудовані VNC/RDP/SPICE",
    "Local Shell": "Локальна оболонка",
    "Snippets...": "Сніпети…",
    "Clusters...": "Кластери…",
    "Templates...": "Шаблони…",
    "Variables...": "Змінні…",
    "Connection History...": "Історія з'єднань…",
    "Statistics...": "Статистика…",
    "Password Generator...": "Генератор паролів…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Імпортувати з'єднання…",
    "Export Connections...": "Експортувати з'єднання…",
    "Copy Connection": "Копіювати з'єднання",
    "Paste Connection": "Вставити з'єднання",
    "Settings": "Налаштування",
    "Flatpak Components...": "Компоненти Flatpak…",
    "About": "Про програму",
    "Quit": "Вийти",
},
"de": {
    "Embedded SSH terminals": "Eingebettete SSH-Terminals",
    "Secure credential storage": "Sichere Anmeldedatenspeicherung",
    "Expect automation": "Expect-Automatisierung",
    "Groups and tags": "Gruppen und Tags",
    "Zero Trust tunnels": "Zero-Trust-Tunnel",
    "Customizable settings": "Anpassbare Einstellungen",
    "Embedded & external clients": "Eingebettete und externe Clients",
    "New connection": "Neue Verbindung",
    "New group": "Neue Gruppe",
    "Local shell": "Lokale Shell",
    "Quick connect": "Schnellverbindung",
    "Search": "Suche",
    "Split vertical": "Vertikal teilen",
    "Split horizontal": "Horizontal teilen",
    "Next tab": "Nächster Tab",
    "Smart search caching": "Intelligentes Such-Caching",
    "Lazy loading for trees": "Lazy Loading für Bäume",
    "Virtual scrolling": "Virtuelles Scrollen",
    "Embedded VNC/RDP/SPICE": "Eingebettetes VNC/RDP/SPICE",
    "Local Shell": "Lokale Shell",
    "Snippets...": "Snippets…",
    "Clusters...": "Cluster…",
    "Templates...": "Vorlagen…",
    "Variables...": "Variablen…",
    "Connection History...": "Verbindungsverlauf…",
    "Statistics...": "Statistiken…",
    "Password Generator...": "Passwortgenerator…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Verbindungen importieren…",
    "Export Connections...": "Verbindungen exportieren…",
    "Copy Connection": "Verbindung kopieren",
    "Paste Connection": "Verbindung einfügen",
    "Settings": "Einstellungen",
    "Flatpak Components...": "Flatpak-Komponenten…",
    "About": "Über",
    "Quit": "Beenden",
},
"fr": {
    "Embedded SSH terminals": "Terminaux SSH intégrés",
    "Secure credential storage": "Stockage sécurisé des identifiants",
    "Expect automation": "Automatisation Expect",
    "Groups and tags": "Groupes et étiquettes",
    "Zero Trust tunnels": "Tunnels Zero Trust",
    "Customizable settings": "Paramètres personnalisables",
    "Embedded & external clients": "Clients intégrés et externes",
    "New connection": "Nouvelle connexion",
    "New group": "Nouveau groupe",
    "Local shell": "Shell local",
    "Quick connect": "Connexion rapide",
    "Search": "Rechercher",
    "Split vertical": "Diviser verticalement",
    "Split horizontal": "Diviser horizontalement",
    "Next tab": "Onglet suivant",
    "Smart search caching": "Cache de recherche intelligent",
    "Lazy loading for trees": "Chargement différé des arborescences",
    "Virtual scrolling": "Défilement virtuel",
    "Embedded VNC/RDP/SPICE": "VNC/RDP/SPICE intégrés",
    "Local Shell": "Shell local",
    "Snippets...": "Snippets…",
    "Clusters...": "Clusters…",
    "Templates...": "Modèles…",
    "Variables...": "Variables…",
    "Connection History...": "Historique des connexions…",
    "Statistics...": "Statistiques…",
    "Password Generator...": "Générateur de mots de passe…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importer des connexions…",
    "Export Connections...": "Exporter des connexions…",
    "Copy Connection": "Copier la connexion",
    "Paste Connection": "Coller la connexion",
    "Settings": "Paramètres",
    "Flatpak Components...": "Composants Flatpak…",
    "About": "À propos",
    "Quit": "Quitter",
},
"es": {
    "Embedded SSH terminals": "Terminales SSH integrados",
    "Secure credential storage": "Almacenamiento seguro de credenciales",
    "Expect automation": "Automatización Expect",
    "Groups and tags": "Grupos y etiquetas",
    "Zero Trust tunnels": "Túneles Zero Trust",
    "Customizable settings": "Configuración personalizable",
    "Embedded & external clients": "Clientes integrados y externos",
    "New connection": "Nueva conexión",
    "New group": "Nuevo grupo",
    "Local shell": "Shell local",
    "Quick connect": "Conexión rápida",
    "Search": "Buscar",
    "Split vertical": "Dividir verticalmente",
    "Split horizontal": "Dividir horizontalmente",
    "Next tab": "Siguiente pestaña",
    "Smart search caching": "Caché de búsqueda inteligente",
    "Lazy loading for trees": "Carga diferida de árboles",
    "Virtual scrolling": "Desplazamiento virtual",
    "Embedded VNC/RDP/SPICE": "VNC/RDP/SPICE integrados",
    "Local Shell": "Shell local",
    "Snippets...": "Snippets…",
    "Clusters...": "Clústeres…",
    "Templates...": "Plantillas…",
    "Variables...": "Variables…",
    "Connection History...": "Historial de conexiones…",
    "Statistics...": "Estadísticas…",
    "Password Generator...": "Generador de contraseñas…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importar conexiones…",
    "Export Connections...": "Exportar conexiones…",
    "Copy Connection": "Copiar conexión",
    "Paste Connection": "Pegar conexión",
    "Settings": "Configuración",
    "Flatpak Components...": "Componentes Flatpak…",
    "About": "Acerca de",
    "Quit": "Salir",
},
"it": {
    "Embedded SSH terminals": "Terminali SSH integrati",
    "Secure credential storage": "Archiviazione sicura delle credenziali",
    "Expect automation": "Automazione Expect",
    "Groups and tags": "Gruppi e tag",
    "Zero Trust tunnels": "Tunnel Zero Trust",
    "Customizable settings": "Impostazioni personalizzabili",
    "Embedded & external clients": "Client integrati ed esterni",
    "New connection": "Nuova connessione",
    "New group": "Nuovo gruppo",
    "Local shell": "Shell locale",
    "Quick connect": "Connessione rapida",
    "Search": "Cerca",
    "Split vertical": "Dividi verticalmente",
    "Split horizontal": "Dividi orizzontalmente",
    "Next tab": "Scheda successiva",
    "Smart search caching": "Cache di ricerca intelligente",
    "Lazy loading for trees": "Caricamento differito degli alberi",
    "Virtual scrolling": "Scorrimento virtuale",
    "Embedded VNC/RDP/SPICE": "VNC/RDP/SPICE integrati",
    "Local Shell": "Shell locale",
    "Snippets...": "Snippet…",
    "Clusters...": "Cluster…",
    "Templates...": "Modelli…",
    "Variables...": "Variabili…",
    "Connection History...": "Cronologia connessioni…",
    "Statistics...": "Statistiche…",
    "Password Generator...": "Generatore di password…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importa connessioni…",
    "Export Connections...": "Esporta connessioni…",
    "Copy Connection": "Copia connessione",
    "Paste Connection": "Incolla connessione",
    "Settings": "Impostazioni",
    "Flatpak Components...": "Componenti Flatpak…",
    "About": "Informazioni",
    "Quit": "Esci",
},
"pl": {
    "Embedded SSH terminals": "Wbudowane terminale SSH",
    "Secure credential storage": "Bezpieczne przechowywanie danych logowania",
    "Expect automation": "Automatyzacja Expect",
    "Groups and tags": "Grupy i tagi",
    "Zero Trust tunnels": "Tunele Zero Trust",
    "Customizable settings": "Konfigurowalne ustawienia",
    "Embedded & external clients": "Wbudowani i zewnętrzni klienci",
    "New connection": "Nowe połączenie",
    "New group": "Nowa grupa",
    "Local shell": "Lokalna powłoka",
    "Quick connect": "Szybkie połączenie",
    "Search": "Szukaj",
    "Split vertical": "Podziel pionowo",
    "Split horizontal": "Podziel poziomo",
    "Next tab": "Następna karta",
    "Smart search caching": "Inteligentne buforowanie wyszukiwania",
    "Lazy loading for trees": "Leniwe ładowanie drzew",
    "Virtual scrolling": "Wirtualne przewijanie",
    "Embedded VNC/RDP/SPICE": "Wbudowane VNC/RDP/SPICE",
    "Local Shell": "Lokalna powłoka",
    "Snippets...": "Snippety…",
    "Clusters...": "Klastry…",
    "Templates...": "Szablony…",
    "Variables...": "Zmienne…",
    "Connection History...": "Historia połączeń…",
    "Statistics...": "Statystyki…",
    "Password Generator...": "Generator haseł…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importuj połączenia…",
    "Export Connections...": "Eksportuj połączenia…",
    "Copy Connection": "Kopiuj połączenie",
    "Paste Connection": "Wklej połączenie",
    "Settings": "Ustawienia",
    "Flatpak Components...": "Komponenty Flatpak…",
    "About": "O programie",
    "Quit": "Zakończ",
},
"pt": {
    "Embedded SSH terminals": "Terminais SSH integrados",
    "Secure credential storage": "Armazenamento seguro de credenciais",
    "Expect automation": "Automação Expect",
    "Groups and tags": "Grupos e etiquetas",
    "Zero Trust tunnels": "Túneis Zero Trust",
    "Customizable settings": "Configurações personalizáveis",
    "Embedded & external clients": "Clientes integrados e externos",
    "New connection": "Nova conexão",
    "New group": "Novo grupo",
    "Local shell": "Shell local",
    "Quick connect": "Conexão rápida",
    "Search": "Pesquisar",
    "Split vertical": "Dividir verticalmente",
    "Split horizontal": "Dividir horizontalmente",
    "Next tab": "Próxima aba",
    "Smart search caching": "Cache de pesquisa inteligente",
    "Lazy loading for trees": "Carregamento preguiçoso de árvores",
    "Virtual scrolling": "Rolagem virtual",
    "Embedded VNC/RDP/SPICE": "VNC/RDP/SPICE integrados",
    "Local Shell": "Shell local",
    "Snippets...": "Snippets…",
    "Clusters...": "Clusters…",
    "Templates...": "Modelos…",
    "Variables...": "Variáveis…",
    "Connection History...": "Histórico de conexões…",
    "Statistics...": "Estatísticas…",
    "Password Generator...": "Gerador de senhas…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importar conexões…",
    "Export Connections...": "Exportar conexões…",
    "Copy Connection": "Copiar conexão",
    "Paste Connection": "Colar conexão",
    "Settings": "Configurações",
    "Flatpak Components...": "Componentes Flatpak…",
    "About": "Sobre",
    "Quit": "Sair",
},
"cs": {
    "Embedded SSH terminals": "Vestavěné SSH terminály",
    "Secure credential storage": "Bezpečné úložiště přihlašovacích údajů",
    "Expect automation": "Automatizace Expect",
    "Groups and tags": "Skupiny a štítky",
    "Zero Trust tunnels": "Tunely Zero Trust",
    "Customizable settings": "Přizpůsobitelná nastavení",
    "Embedded & external clients": "Vestavění a externí klienti",
    "New connection": "Nové připojení",
    "New group": "Nová skupina",
    "Local shell": "Místní shell",
    "Quick connect": "Rychlé připojení",
    "Search": "Hledat",
    "Split vertical": "Rozdělit svisle",
    "Split horizontal": "Rozdělit vodorovně",
    "Next tab": "Další záložka",
    "Smart search caching": "Inteligentní mezipaměť vyhledávání",
    "Lazy loading for trees": "Líné načítání stromů",
    "Virtual scrolling": "Virtuální posouvání",
    "Embedded VNC/RDP/SPICE": "Vestavěné VNC/RDP/SPICE",
    "Local Shell": "Místní shell",
    "Snippets...": "Snippety…",
    "Clusters...": "Clustery…",
    "Templates...": "Šablony…",
    "Variables...": "Proměnné…",
    "Connection History...": "Historie připojení…",
    "Statistics...": "Statistiky…",
    "Password Generator...": "Generátor hesel…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importovat připojení…",
    "Export Connections...": "Exportovat připojení…",
    "Copy Connection": "Kopírovat připojení",
    "Paste Connection": "Vložit připojení",
    "Settings": "Nastavení",
    "Flatpak Components...": "Komponenty Flatpak…",
    "About": "O aplikaci",
    "Quit": "Ukončit",
},
"sk": {
    "Embedded SSH terminals": "Vstavané SSH terminály",
    "Secure credential storage": "Bezpečné úložisko prihlasovacích údajov",
    "Expect automation": "Automatizácia Expect",
    "Groups and tags": "Skupiny a štítky",
    "Zero Trust tunnels": "Tunely Zero Trust",
    "Customizable settings": "Prispôsobiteľné nastavenia",
    "Embedded & external clients": "Vstavaní a externí klienti",
    "New connection": "Nové pripojenie",
    "New group": "Nová skupina",
    "Local shell": "Miestny shell",
    "Quick connect": "Rýchle pripojenie",
    "Search": "Hľadať",
    "Split vertical": "Rozdeliť zvisle",
    "Split horizontal": "Rozdeliť vodorovne",
    "Next tab": "Ďalšia karta",
    "Smart search caching": "Inteligentné ukladanie vyhľadávania",
    "Lazy loading for trees": "Lenivé načítanie stromov",
    "Virtual scrolling": "Virtuálne posúvanie",
    "Embedded VNC/RDP/SPICE": "Vstavané VNC/RDP/SPICE",
    "Local Shell": "Miestny shell",
    "Snippets...": "Snippety…",
    "Clusters...": "Klastre…",
    "Templates...": "Šablóny…",
    "Variables...": "Premenné…",
    "Connection History...": "História pripojení…",
    "Statistics...": "Štatistiky…",
    "Password Generator...": "Generátor hesiel…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importovať pripojenia…",
    "Export Connections...": "Exportovať pripojenia…",
    "Copy Connection": "Kopírovať pripojenie",
    "Paste Connection": "Vložiť pripojenie",
    "Settings": "Nastavenia",
    "Flatpak Components...": "Komponenty Flatpak…",
    "About": "O aplikácii",
    "Quit": "Ukončiť",
},
"da": {
    "Embedded SSH terminals": "Indlejrede SSH-terminaler",
    "Secure credential storage": "Sikker lagring af legitimationsoplysninger",
    "Expect automation": "Expect-automatisering",
    "Groups and tags": "Grupper og tags",
    "Zero Trust tunnels": "Zero Trust-tunneler",
    "Customizable settings": "Tilpasselige indstillinger",
    "Embedded & external clients": "Indlejrede og eksterne klienter",
    "New connection": "Ny forbindelse",
    "New group": "Ny gruppe",
    "Local shell": "Lokal shell",
    "Quick connect": "Hurtig forbindelse",
    "Search": "Søg",
    "Split vertical": "Del lodret",
    "Split horizontal": "Del vandret",
    "Next tab": "Næste fane",
    "Smart search caching": "Intelligent søgecache",
    "Lazy loading for trees": "Doven indlæsning af træer",
    "Virtual scrolling": "Virtuel rulning",
    "Embedded VNC/RDP/SPICE": "Indlejret VNC/RDP/SPICE",
    "Local Shell": "Lokal shell",
    "Snippets...": "Snippets…",
    "Clusters...": "Klynger…",
    "Templates...": "Skabeloner…",
    "Variables...": "Variabler…",
    "Connection History...": "Forbindelseshistorik…",
    "Statistics...": "Statistik…",
    "Password Generator...": "Adgangskodegenerator…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importér forbindelser…",
    "Export Connections...": "Eksportér forbindelser…",
    "Copy Connection": "Kopiér forbindelse",
    "Paste Connection": "Indsæt forbindelse",
    "Settings": "Indstillinger",
    "Flatpak Components...": "Flatpak-komponenter…",
    "About": "Om",
    "Quit": "Afslut",
},
"sv": {
    "Embedded SSH terminals": "Inbäddade SSH-terminaler",
    "Secure credential storage": "Säker lagring av autentiseringsuppgifter",
    "Expect automation": "Expect-automatisering",
    "Groups and tags": "Grupper och taggar",
    "Zero Trust tunnels": "Zero Trust-tunnlar",
    "Customizable settings": "Anpassningsbara inställningar",
    "Embedded & external clients": "Inbäddade och externa klienter",
    "New connection": "Ny anslutning",
    "New group": "Ny grupp",
    "Local shell": "Lokalt skal",
    "Quick connect": "Snabbanslutning",
    "Search": "Sök",
    "Split vertical": "Dela vertikalt",
    "Split horizontal": "Dela horisontellt",
    "Next tab": "Nästa flik",
    "Smart search caching": "Intelligent sökcache",
    "Lazy loading for trees": "Lat inläsning av träd",
    "Virtual scrolling": "Virtuell rullning",
    "Embedded VNC/RDP/SPICE": "Inbäddat VNC/RDP/SPICE",
    "Local Shell": "Lokalt skal",
    "Snippets...": "Snippets…",
    "Clusters...": "Kluster…",
    "Templates...": "Mallar…",
    "Variables...": "Variabler…",
    "Connection History...": "Anslutningshistorik…",
    "Statistics...": "Statistik…",
    "Password Generator...": "Lösenordsgenerator…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Importera anslutningar…",
    "Export Connections...": "Exportera anslutningar…",
    "Copy Connection": "Kopiera anslutning",
    "Paste Connection": "Klistra in anslutning",
    "Settings": "Inställningar",
    "Flatpak Components...": "Flatpak-komponenter…",
    "About": "Om",
    "Quit": "Avsluta",
},
"nl": {
    "Embedded SSH terminals": "Ingebedde SSH-terminals",
    "Secure credential storage": "Veilige opslag van inloggegevens",
    "Expect automation": "Expect-automatisering",
    "Groups and tags": "Groepen en tags",
    "Zero Trust tunnels": "Zero Trust-tunnels",
    "Customizable settings": "Aanpasbare instellingen",
    "Embedded & external clients": "Ingebedde en externe clients",
    "New connection": "Nieuwe verbinding",
    "New group": "Nieuwe groep",
    "Local shell": "Lokale shell",
    "Quick connect": "Snelverbinding",
    "Search": "Zoeken",
    "Split vertical": "Verticaal splitsen",
    "Split horizontal": "Horizontaal splitsen",
    "Next tab": "Volgend tabblad",
    "Smart search caching": "Slim zoeken met cache",
    "Lazy loading for trees": "Lui laden van boomstructuren",
    "Virtual scrolling": "Virtueel scrollen",
    "Embedded VNC/RDP/SPICE": "Ingebed VNC/RDP/SPICE",
    "Local Shell": "Lokale shell",
    "Snippets...": "Snippets…",
    "Clusters...": "Clusters…",
    "Templates...": "Sjablonen…",
    "Variables...": "Variabelen…",
    "Connection History...": "Verbindingsgeschiedenis…",
    "Statistics...": "Statistieken…",
    "Password Generator...": "Wachtwoordgenerator…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Verbindingen importeren…",
    "Export Connections...": "Verbindingen exporteren…",
    "Copy Connection": "Verbinding kopiëren",
    "Paste Connection": "Verbinding plakken",
    "Settings": "Instellingen",
    "Flatpak Components...": "Flatpak-componenten…",
    "About": "Over",
    "Quit": "Afsluiten",
},
"be": {
    "Embedded SSH terminals": "Убудаваныя SSH-тэрміналы",
    "Secure credential storage": "Бяспечнае захоўванне ўліковых даных",
    "Expect automation": "Аўтаматызацыя Expect",
    "Groups and tags": "Групы і тэгі",
    "Zero Trust tunnels": "Тунэлі Zero Trust",
    "Customizable settings": "Наладжвальныя параметры",
    "Embedded & external clients": "Убудаваныя і знешнія кліенты",
    "New connection": "Новае злучэнне",
    "New group": "Новая група",
    "Local shell": "Лакальная абалонка",
    "Quick connect": "Хуткае злучэнне",
    "Search": "Пошук",
    "Split vertical": "Падзяліць вертыкальна",
    "Split horizontal": "Падзяліць гарызантальна",
    "Next tab": "Наступная ўкладка",
    "Smart search caching": "Разумнае кэшаванне пошуку",
    "Lazy loading for trees": "Лянівая загрузка дрэў",
    "Virtual scrolling": "Віртуальная пракрутка",
    "Embedded VNC/RDP/SPICE": "Убудаваныя VNC/RDP/SPICE",
    "Local Shell": "Лакальная абалонка",
    "Snippets...": "Сніпеты…",
    "Clusters...": "Кластары…",
    "Templates...": "Шаблоны…",
    "Variables...": "Зменныя…",
    "Connection History...": "Гісторыя злучэнняў…",
    "Statistics...": "Статыстыка…",
    "Password Generator...": "Генератар пароляў…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Імпартаваць злучэнні…",
    "Export Connections...": "Экспартаваць злучэнні…",
    "Copy Connection": "Капіяваць злучэнне",
    "Paste Connection": "Уставіць злучэнне",
    "Settings": "Налады",
    "Flatpak Components...": "Кампаненты Flatpak…",
    "About": "Пра праграму",
    "Quit": "Выйсці",
},
"kk": {
    "Embedded SSH terminals": "Кірістірілген SSH терминалдары",
    "Secure credential storage": "Тіркелгі деректерін қауіпсіз сақтау",
    "Expect automation": "Expect автоматтандыру",
    "Groups and tags": "Топтар мен тегтер",
    "Zero Trust tunnels": "Zero Trust туннельдері",
    "Customizable settings": "Баптауларды теңшеу",
    "Embedded & external clients": "Кірістірілген және сыртқы клиенттер",
    "New connection": "Жаңа қосылым",
    "New group": "Жаңа топ",
    "Local shell": "Жергілікті қабықша",
    "Quick connect": "Жылдам қосылу",
    "Search": "Іздеу",
    "Split vertical": "Тігінен бөлу",
    "Split horizontal": "Көлденеңінен бөлу",
    "Next tab": "Келесі қойынды",
    "Smart search caching": "Ақылды іздеу кэші",
    "Lazy loading for trees": "Ағаштарды жалқау жүктеу",
    "Virtual scrolling": "Виртуалды айналдыру",
    "Embedded VNC/RDP/SPICE": "Кірістірілген VNC/RDP/SPICE",
    "Local Shell": "Жергілікті қабықша",
    "Snippets...": "Сніпеттер…",
    "Clusters...": "Кластерлер…",
    "Templates...": "Үлгілер…",
    "Variables...": "Айнымалылар…",
    "Connection History...": "Қосылым тарихы…",
    "Statistics...": "Статистика…",
    "Password Generator...": "Құпия сөз генераторы…",
    "Wake On LAN...": "Wake On LAN…",
    "Import Connections...": "Қосылымдарды импорттау…",
    "Export Connections...": "Қосылымдарды экспорттау…",
    "Copy Connection": "Қосылымды көшіру",
    "Paste Connection": "Қосылымды қою",
    "Settings": "Баптаулар",
    "Flatpak Components...": "Flatpak компоненттері…",
    "About": "Бағдарлама туралы",
    "Quit": "Шығу",
},
}


def apply_to_po(filepath, lang):
    """Fill empty msgstr entries in a .po file from the dictionary."""
    trans = TRANSLATIONS.get(lang)
    if not trans:
        print(f"  SKIP {lang}: no dictionary")
        return 0
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()
    filled = 0
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("msgid "):
            msgid_val = extract_string(lines, i)
            # Find corresponding msgstr
            j = i + 1
            while j < len(lines) and not lines[j].startswith("msgstr "):
                j += 1
            if j < len(lines):
                msgstr_val = extract_string(lines, j)
                if msgstr_val == "" and msgid_val in trans:
                    lines[j] = f'msgstr "{escape_po(trans[msgid_val])}"\n'
                    filled += 1
        i += 1
    with open(filepath, "w", encoding="utf-8") as f:
        f.writelines(lines)
    return filled


def extract_string(lines, start):
    """Extract a msgid/msgstr value, handling multi-line strings."""
    line = lines[start]
    # Get the part after msgid/msgstr
    m = re.match(r'(?:msgid|msgstr)\s+"(.*)"', line)
    if not m:
        return ""
    val = unescape_po(m.group(1))
    # Check for continuation lines
    j = start + 1
    while j < len(lines) and lines[j].startswith('"'):
        m2 = re.match(r'"(.*)"', lines[j])
        if m2:
            val += unescape_po(m2.group(1))
        j += 1
    return val


def escape_po(s):
    """Escape a string for .po file."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def unescape_po(s):
    """Unescape a .po string."""
    return s.replace('\\"', '"').replace("\\\\", "\\")


if __name__ == "__main__":
    po_dir = os.path.dirname(os.path.abspath(__file__))
    total = 0
    for po_file in sorted(os.listdir(po_dir)):
        if not po_file.endswith(".po"):
            continue
        lang = po_file[:-3]
        filepath = os.path.join(po_dir, po_file)
        filled = apply_to_po(filepath, lang)
        total += filled
        print(f"  {lang}.po: filled {filled} entries")
    print(f"\nTotal: {total} entries filled across all languages.")
