name: rustconn
base: core24
version: '0.7.7'
summary: Manage remote connections easily
description: |
  RustConn is a modern connection manager for Linux with a GTK4/Wayland-native
  interface. Manage SSH, RDP, VNC, SPICE, and Zero Trust connections from a
  single application.

  Protocols (embedded Rust implementations):
  - SSH with embedded VTE terminal and split view
  - RDP via IronRDP (embedded)
  - VNC via vnc-rs (embedded)
  - SPICE via external remote-viewer (install on host)

  Zero Trust (install CLIs on host):
  - AWS SSM, GCP IAP, Azure Bastion, OCI Bastion
  - Cloudflare Tunnel, Teleport, Tailscale, Boundary

  Organization:
  - Groups, tags, and templates
  - Connection history and statistics
  - Session logging

  Import/Export:
  - Asbru-CM, Remmina, SSH config, Ansible inventory
  - Royal TS, MobaXterm, native format (.rcn)

  Security:
  - KeePassXC (KDBX files)
  - libsecret (GNOME Keyring)
  - Bitwarden CLI, 1Password CLI (install on host)

  Productivity:
  - Split terminals
  - Command snippets
  - Cluster commands
  - Wake-on-LAN

  Note: This snap uses strict confinement with embedded protocol clients.
  External CLIs (Zero Trust, password managers) must be installed on host
  and accessed via system-files interface.

grade: stable
confinement: strict
icon: rustconn/assets/icons/hicolor/256x256/apps/io.github.totoshko88.RustConn.png
license: GPL-3.0+
website: https://github.com/totoshko88/RustConn
source-code: https://github.com/totoshko88/RustConn
issues: https://github.com/totoshko88/RustConn/issues
donation: https://ko-fi.com/totoshko88
contact: totoshko88@gmail.com

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1
  /usr/share/xml/iso-codes:
    bind: $SNAP/usr/share/xml/iso-codes
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/glib-2.0/schemas:
    bind: $SNAP/usr/share/glib-2.0/schemas

plugs:
  # GTK/Desktop integration via content snaps
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

  # SSH keys access
  ssh-keys:
    interface: ssh-keys

  # Cloud provider credentials
  aws-credentials:
    interface: personal-files
    read:
      - $HOME/.aws
  gcloud-credentials:
    interface: personal-files
    read:
      - $HOME/.config/gcloud
  azure-credentials:
    interface: personal-files
    read:
      - $HOME/.azure
  oci-credentials:
    interface: personal-files
    read:
      - $HOME/.oci

  # Host CLI access for Zero Trust and password managers
  host-usr-bin:
    interface: system-files
    read:
      - /usr/bin/aws
      - /usr/bin/gcloud
      - /usr/bin/az
      - /usr/bin/oci
      - /usr/bin/cloudflared
      - /usr/bin/tsh
      - /usr/bin/tailscale
      - /usr/bin/boundary
      - /usr/bin/bw
      - /usr/bin/op
      - /usr/bin/keepassxc-proxy
      - /usr/bin/remote-viewer
      - /usr/bin/xfreerdp
      - /usr/bin/vncviewer

apps:
  rustconn:
    command: usr/bin/rustconn-wrapper
    desktop: usr/share/applications/io.github.totoshko88.RustConn.desktop
    common-id: io.github.totoshko88.RustConn
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - audio-playback
      - network
      - network-bind
      - home
      - ssh-keys
      - password-manager-service
      - gtk-3-themes
      - icon-themes
      - sound-themes
      - aws-credentials
      - gcloud-credentials
      - azure-credentials
      - oci-credentials
      - host-usr-bin
    environment:
      GTK_USE_PORTAL: "1"
      GDK_BACKEND: wayland,x11
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
      GIO_MODULE_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gio/modules
      GDK_PIXBUF_MODULE_FILE: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0/loaders.cache
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
      FONTCONFIG_PATH: $SNAP/etc/fonts
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

  rustconn-cli:
    command: usr/bin/rustconn-cli
    plugs:
      - network
      - home
      - ssh-keys
      - aws-credentials
      - gcloud-credentials
      - azure-credentials
      - oci-credentials
      - host-usr-bin

parts:
  rustconn:
    plugin: rust
    source: .
    rust-channel: "1.88"
    rust-path: [rustconn, rustconn-cli]
    rust-use-global-lto: true
    build-packages:
      - libgtk-4-dev
      - libadwaita-1-dev
      - libvte-2.91-gtk4-dev
      - libssl-dev
      - libasound2-dev
      - pkg-config
      - clang
      - cmake
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - libvte-2.91-gtk4-0
      - libasound2t64
      - libssl3t64
      - openssh-client
      - libgraphene-1.0-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libharfbuzz0b
      - libcairo2
      - libcairo-gobject2
      - libgdk-pixbuf-2.0-0
      - librsvg2-2
      - librsvg2-common
      - shared-mime-info
      - gsettings-desktop-schemas
      - libglib2.0-bin
      - fontconfig
      - fonts-dejavu-core
    organize:
      bin/rustconn: usr/bin/rustconn
      bin/rustconn-cli: usr/bin/rustconn-cli
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons
      mkdir -p $CRAFT_PART_INSTALL/usr/share/metainfo
      cp rustconn/assets/io.github.totoshko88.RustConn.desktop $CRAFT_PART_INSTALL/usr/share/applications/
      cp rustconn/assets/io.github.totoshko88.RustConn.metainfo.xml $CRAFT_PART_INSTALL/usr/share/metainfo/
      cp -r rustconn/assets/icons/hicolor $CRAFT_PART_INSTALL/usr/share/icons/
    override-prime: |
      craftctl default
      # Update gdk-pixbuf loaders cache
      if [ -d usr/lib/*/gdk-pixbuf-2.0 ]; then
        /usr/lib/*/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > usr/lib/*/gdk-pixbuf-2.0/2.10.0/loaders.cache 2>/dev/null || true
      fi
      # Compile GSettings schemas
      if [ -d usr/share/glib-2.0/schemas ]; then
        glib-compile-schemas usr/share/glib-2.0/schemas 2>/dev/null || true
      fi

  wrapper:
    plugin: dump
    source: snap/local
    organize:
      rustconn-wrapper: usr/bin/rustconn-wrapper
