//! Command handler modules for the CLI.

mod add;
mod cloud_sync;
mod cluster;
mod completions;
mod connect;
mod delete;
mod duplicate;
mod dynamic_folder;
mod export_import;
mod group;
mod history;
mod list;
mod manpage;
mod monitor;
mod move_cmd;
mod pin;
mod recording;
mod secret;
mod sftp;
mod show;
mod smart_folder;
mod snippet;
mod stats;
mod sync;
mod tag;
mod template;
mod test;
mod update;
mod variable;
mod wol;

use std::path::Path;

use crate::cli::Commands;
use crate::error::CliError;

/// Dispatch a CLI command to the appropriate handler.
#[allow(clippy::too_many_lines)]
pub fn dispatch(config_path: Option<&Path>, command: Commands) -> Result<(), CliError> {
    match command {
        Commands::List {
            format,
            protocol,
            group,
            tag,
        } => list::cmd_list(
            config_path,
            format.effective(),
            protocol.as_deref(),
            group.as_deref(),
            tag.as_deref(),
        ),
        Commands::Connect { name, dry_run } => connect::cmd_connect(config_path, &name, dry_run),
        Commands::Add {
            name,
            host,
            port,
            protocol,
            user,
            key,
            auth_method,
            device,
            baud_rate,
            icon,
            ssh_agent_socket,
            provider,
            hoop_connection_name,
            hoop_gateway_url,
            hoop_grpc_url,
            aws_profile,
            aws_region,
            gcp_zone,
            gcp_project,
            resource_group,
            bastion_name,
            vm_name,
            bastion_id,
            target_resource_id,
            target_private_ip,
            teleport_cluster,
            boundary_target,
            boundary_addr,
            custom_command,
            jump_host,
            keep_alive_interval,
            keep_alive_count,
            ssh_verbose,
            ignore_certificate,
            tags,
            description,
            group,
            domain,
            window_mode,
            skip_port_check,
            x11_forwarding,
            agent_forwarding,
            compression,
            startup_command,
            proxy_command,
            ssh_option,
            local_forward,
            remote_forward,
            dynamic_forward,
            gateway,
            gateway_port,
            gateway_username,
            remote_app_program,
            remote_app_args,
            remote_app_name,
            resolution,
            color_depth,
            disable_nla,
            keyboard_layout,
            audio_redirect,
            shared_folder,
            vnc_client_mode,
            vnc_performance,
            vnc_encoding,
            vnc_compression,
            vnc_quality,
            vnc_view_only,
            vnc_no_scaling,
            vnc_no_clipboard,
            vnc_custom_arg,
            spice_tls,
            spice_ca_cert,
            spice_skip_cert_verify,
            spice_usb_redirection,
            spice_no_clipboard,
            spice_image_compression,
            spice_proxy,
            spice_shared_folder,
            mosh_ssh_port,
            mosh_port_range,
            mosh_server_binary,
            mosh_predict,
            mosh_custom_arg,
            serial_data_bits,
            serial_stop_bits,
            serial_parity,
            serial_flow_control,
            serial_custom_arg,
        } => add::cmd_add(
            config_path,
            add::AddParams {
                name: &name,
                host: &host,
                port,
                protocol: &protocol,
                user: user.as_deref(),
                key: key.as_deref(),
                auth_method: auth_method.as_deref(),
                device: device.as_deref(),
                baud_rate,
                icon: icon.as_deref(),
                ssh_agent_socket: ssh_agent_socket.as_deref(),
                provider: provider.as_deref(),
                hoop_connection_name: hoop_connection_name.as_deref(),
                hoop_gateway_url: hoop_gateway_url.as_deref(),
                hoop_grpc_url: hoop_grpc_url.as_deref(),
                aws_profile: aws_profile.as_deref(),
                aws_region: aws_region.as_deref(),
                gcp_zone: gcp_zone.as_deref(),
                gcp_project: gcp_project.as_deref(),
                resource_group: resource_group.as_deref(),
                bastion_name: bastion_name.as_deref(),
                vm_name: vm_name.as_deref(),
                bastion_id: bastion_id.as_deref(),
                target_resource_id: target_resource_id.as_deref(),
                target_private_ip: target_private_ip.as_deref(),
                teleport_cluster: teleport_cluster.as_deref(),
                boundary_target: boundary_target.as_deref(),
                boundary_addr: boundary_addr.as_deref(),
                custom_command: custom_command.as_deref(),
                jump_host: jump_host.as_deref(),
                keep_alive_interval,
                keep_alive_count,
                ssh_verbose,
                ignore_certificate,
                tags: tags.as_deref(),
                description: description.as_deref(),
                group: group.as_deref(),
                domain: domain.as_deref(),
                window_mode: window_mode.as_deref(),
                skip_port_check,
                x11_forwarding,
                agent_forwarding,
                compression,
                startup_command: startup_command.as_deref(),
                proxy_command: proxy_command.as_deref(),
                ssh_option: &ssh_option,
                local_forward: &local_forward,
                remote_forward: &remote_forward,
                dynamic_forward: &dynamic_forward,
                gateway: gateway.as_deref(),
                gateway_port,
                gateway_username: gateway_username.as_deref(),
                remote_app_program: remote_app_program.as_deref(),
                remote_app_args: remote_app_args.as_deref(),
                remote_app_name: remote_app_name.as_deref(),
                resolution: resolution.as_deref(),
                color_depth,
                disable_nla,
                keyboard_layout,
                audio_redirect,
                shared_folder: &shared_folder,
                vnc_client_mode: vnc_client_mode.as_deref(),
                vnc_performance: vnc_performance.as_deref(),
                vnc_encoding: vnc_encoding.as_deref(),
                vnc_compression,
                vnc_quality,
                vnc_view_only,
                vnc_no_scaling,
                vnc_no_clipboard,
                vnc_custom_arg: &vnc_custom_arg,
                spice_tls,
                spice_ca_cert: spice_ca_cert.as_deref(),
                spice_skip_cert_verify,
                spice_usb_redirection,
                spice_no_clipboard,
                spice_image_compression: spice_image_compression.as_deref(),
                spice_proxy: spice_proxy.as_deref(),
                spice_shared_folder: &spice_shared_folder,
                mosh_ssh_port,
                mosh_port_range: mosh_port_range.as_deref(),
                mosh_server_binary: mosh_server_binary.as_deref(),
                mosh_predict: mosh_predict.as_deref(),
                mosh_custom_arg: &mosh_custom_arg,
                serial_data_bits: serial_data_bits.as_deref(),
                serial_stop_bits: serial_stop_bits.as_deref(),
                serial_parity: serial_parity.as_deref(),
                serial_flow_control: serial_flow_control.as_deref(),
                serial_custom_arg: &serial_custom_arg,
            },
        ),
        Commands::Export {
            format,
            output,
            csv_delimiter,
            csv_fields,
        } => export_import::cmd_export(
            config_path,
            format,
            &output,
            csv_delimiter.as_deref(),
            csv_fields.as_deref(),
        ),
        Commands::Import {
            format,
            file,
            auto,
            dry_run,
        } => export_import::cmd_import(config_path, format, file.as_deref(), auto, dry_run),
        Commands::Test {
            name,
            timeout,
            format,
        } => test::cmd_test(config_path, &name, timeout, format.effective()),
        Commands::Delete { name, force } => delete::cmd_delete(config_path, &name, force),
        Commands::Show { name, format } => show::cmd_show(config_path, &name, format.effective()),
        Commands::Update {
            name,
            new_name,
            host,
            port,
            user,
            key,
            auth_method,
            device,
            baud_rate,
            icon,
            ssh_agent_socket,
            provider,
            hoop_connection_name,
            hoop_gateway_url,
            hoop_grpc_url,
            aws_profile,
            aws_region,
            gcp_zone,
            gcp_project,
            resource_group,
            bastion_name,
            vm_name,
            bastion_id,
            target_resource_id,
            target_private_ip,
            teleport_cluster,
            boundary_target,
            boundary_addr,
            custom_command,
            jump_host,
            keep_alive_interval,
            keep_alive_count,
            ssh_verbose,
            ignore_certificate,
            tags,
            add_tag,
            remove_tag,
            description,
            group,
            domain,
            window_mode,
            skip_port_check,
            x11_forwarding,
            agent_forwarding,
            compression,
            startup_command,
            proxy_command,
            ssh_option,
            local_forward,
            remote_forward,
            dynamic_forward,
            gateway,
            gateway_port,
            gateway_username,
            remote_app_program,
            remote_app_args,
            remote_app_name,
            resolution,
            color_depth,
            disable_nla,
            keyboard_layout,
            audio_redirect,
            shared_folder,
            vnc_client_mode,
            vnc_performance,
            vnc_encoding,
            vnc_compression,
            vnc_quality,
            vnc_view_only,
            vnc_no_scaling,
            vnc_no_clipboard,
            vnc_custom_arg,
            spice_tls,
            spice_ca_cert,
            spice_skip_cert_verify,
            spice_usb_redirection,
            spice_no_clipboard,
            spice_image_compression,
            spice_proxy,
            spice_shared_folder,
            mosh_ssh_port,
            mosh_port_range,
            mosh_server_binary,
            mosh_predict,
            mosh_custom_arg,
            serial_data_bits,
            serial_stop_bits,
            serial_parity,
            serial_flow_control,
            serial_custom_arg,
        } => update::cmd_update(
            config_path,
            update::UpdateParams {
                name: &name,
                new_name: new_name.as_deref(),
                host: host.as_deref(),
                port,
                user: user.as_deref(),
                key: key.as_deref(),
                auth_method: auth_method.as_deref(),
                device: device.as_deref(),
                baud_rate,
                icon: icon.as_deref(),
                ssh_agent_socket: ssh_agent_socket.as_deref(),
                provider: provider.as_deref(),
                hoop_connection_name: hoop_connection_name.as_deref(),
                hoop_gateway_url: hoop_gateway_url.as_deref(),
                hoop_grpc_url: hoop_grpc_url.as_deref(),
                aws_profile: aws_profile.as_deref(),
                aws_region: aws_region.as_deref(),
                gcp_zone: gcp_zone.as_deref(),
                gcp_project: gcp_project.as_deref(),
                resource_group: resource_group.as_deref(),
                bastion_name: bastion_name.as_deref(),
                vm_name: vm_name.as_deref(),
                bastion_id: bastion_id.as_deref(),
                target_resource_id: target_resource_id.as_deref(),
                target_private_ip: target_private_ip.as_deref(),
                teleport_cluster: teleport_cluster.as_deref(),
                boundary_target: boundary_target.as_deref(),
                boundary_addr: boundary_addr.as_deref(),
                custom_command: custom_command.as_deref(),
                jump_host: jump_host.as_deref(),
                keep_alive_interval,
                keep_alive_count,
                ssh_verbose,
                ignore_certificate,
                tags: tags.as_deref(),
                add_tag: &add_tag,
                remove_tag: &remove_tag,
                description: description.as_deref(),
                group: group.as_deref(),
                domain: domain.as_deref(),
                window_mode: window_mode.as_deref(),
                skip_port_check,
                x11_forwarding,
                agent_forwarding,
                compression,
                startup_command: startup_command.as_deref(),
                proxy_command: proxy_command.as_deref(),
                ssh_option: &ssh_option,
                local_forward: &local_forward,
                remote_forward: &remote_forward,
                dynamic_forward: &dynamic_forward,
                gateway: gateway.as_deref(),
                gateway_port,
                gateway_username: gateway_username.as_deref(),
                remote_app_program: remote_app_program.as_deref(),
                remote_app_args: remote_app_args.as_deref(),
                remote_app_name: remote_app_name.as_deref(),
                resolution: resolution.as_deref(),
                color_depth,
                disable_nla,
                keyboard_layout,
                audio_redirect,
                shared_folder: &shared_folder,
                vnc_client_mode: vnc_client_mode.as_deref(),
                vnc_performance: vnc_performance.as_deref(),
                vnc_encoding: vnc_encoding.as_deref(),
                vnc_compression,
                vnc_quality,
                vnc_view_only,
                vnc_no_scaling,
                vnc_no_clipboard,
                vnc_custom_arg: &vnc_custom_arg,
                spice_tls,
                spice_ca_cert: spice_ca_cert.as_deref(),
                spice_skip_cert_verify,
                spice_usb_redirection,
                spice_no_clipboard,
                spice_image_compression: spice_image_compression.as_deref(),
                spice_proxy: spice_proxy.as_deref(),
                spice_shared_folder: &spice_shared_folder,
                mosh_ssh_port,
                mosh_port_range: mosh_port_range.as_deref(),
                mosh_server_binary: mosh_server_binary.as_deref(),
                mosh_predict: mosh_predict.as_deref(),
                mosh_custom_arg: &mosh_custom_arg,
                serial_data_bits: serial_data_bits.as_deref(),
                serial_stop_bits: serial_stop_bits.as_deref(),
                serial_parity: serial_parity.as_deref(),
                serial_flow_control: serial_flow_control.as_deref(),
                serial_custom_arg: &serial_custom_arg,
            },
        ),
        Commands::Wol {
            target,
            broadcast,
            port,
        } => wol::cmd_wol(config_path, &target, &broadcast, port),
        Commands::Snippet(subcmd) => snippet::cmd_snippet(config_path, subcmd),
        Commands::Group(subcmd) => group::cmd_group(config_path, subcmd),
        Commands::Template(subcmd) => template::cmd_template(config_path, subcmd),
        Commands::Cluster(subcmd) => cluster::cmd_cluster(config_path, subcmd),
        Commands::Var(subcmd) => variable::cmd_var(config_path, subcmd),
        Commands::Secret(subcmd) => secret::cmd_secret(config_path, subcmd),
        Commands::SmartFolder(subcmd) => smart_folder::cmd_smart_folder(config_path, subcmd),
        Commands::DynamicFolder(subcmd) => dynamic_folder::cmd_dynamic_folder(config_path, subcmd),
        Commands::Recording(subcmd) => recording::cmd_recording(subcmd),
        Commands::Duplicate { name, new_name } => {
            duplicate::cmd_duplicate(config_path, &name, new_name.as_deref())
        }
        Commands::Sftp { name, cli, mc } => sftp::cmd_sftp(config_path, &name, cli, mc),
        Commands::Stats { format } => stats::cmd_stats(config_path, format.effective()),
        Commands::Completions { shell } => completions::cmd_completions(shell),
        Commands::ManPage => manpage::cmd_manpage(),
        Commands::Sync(subcmd) => cloud_sync::cmd_cloud_sync(config_path, subcmd),
        Commands::History(subcmd) => history::cmd_history(config_path, subcmd),
        Commands::Pin { name } => pin::cmd_pin(config_path, &name),
        Commands::Unpin { name } => pin::cmd_unpin(config_path, &name),
        Commands::Tag(subcmd) => tag::cmd_tag(config_path, subcmd),
        Commands::Move { name, group } => move_cmd::cmd_move(config_path, &name, &group),
        Commands::Monitor(subcmd) => monitor::cmd_monitor(config_path, subcmd),
    }
}
